### PR TITLE
Fixes for various tickets (MCS-599, MCS-578, MCS-646)

### PR DESCRIPTION
**Pull request by rartiss55**
A bunch of small fixes: Fixing category_type field for history records, adding delta_time field to ingest, updating constants for eval 3.5 rerun.

### CODE REVIEW

**Comment by rartiss55** [comment]
Did some testing and noticed this line: 
https://github.com/NextCenturyCorporation/mcs-ingest/blob/42d6e75b666dd40cc1ad9ab4d6cf42a577f5cfcd/mcs_scene_ingest.py#L343

Wondering if we should add "eval" as well to that check in case we reuse file names for future evals (like if we call another file "delta_0001_01" in the future)?

**Review by brianpippin — APPROVED** [review]
This code looks good, and I trust you on the secondary/tertiary fix, i assume you ingested a new file and made sure it came through okay?

**Review by deanwetherby — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
The code looks good.

**Comment by rartiss55** [comment]
> This code looks good, and I trust you on the secondary/tertiary fix, i assume you ingested a new file and made sure it came through okay?

Yup!

**Comment by rartiss55** [comment]
> Did some testing and noticed this line:
> https://github.com/NextCenturyCorporation/mcs-ingest/blob/42d6e75b666dd40cc1ad9ab4d6cf42a577f5cfcd/mcs_scene_ingest.py#L343
> 
> Wondering if we should add "eval" as well to that check in case we reuse file names for future evals (like if we call another scene file "delta_0001_01" in the future)?

My latest commit addresses this -- added an additional dict since history records have the eval name "evaluation x results" and scene records use "evaluation x scenes"

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
